# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: template.yaml
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/odwyersoftware/brunette
    rev: 0.2.8
    hooks:
      - id: brunette
        types: [python]
        files: "steps/"
  - repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.12.4
    hooks:
      - id: typos
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.97.1"
    hooks:
      - id: terraform_fmt
      # - id: terraform_tflint
      - id: terraform_validate
        args:
          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
