title: Observability & Monitoring for Azure AI Agents Using Application Insights and Log Analytics
description: Observability & Monitoring for Azure AI Agents Using Application Insights and Log Analytics
vendor: azure # aws|azure|google|alibaba-cloud
#custom_policy_tags: # [optional] custom security policy tags (defined in hagrid), string of comma separated values. E.g. azure-vm.mckinsey_instances_count
